name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build packages
        run: |
          yarn build

      - name: Install example dependencies
        uses: bahmutov/npm-install@v1
        working-directory: example

      - name: Run tests
        run: |
          yarn test
        working-directory: example
